// Generated by tools/gen-pac from stm32-metapac 21.0.0 (src/chips/stm32h725ig/metadata.rs).
// Do not edit by hand: change tools/gen-pac and re-run it (FEATURES.md P7a).

//! Addresses and FDCAN RCC bits for `h7` (reference chip STM32H725IG). FDCAN register version `fdcan_h7`.
pub(crate) const FDCAN1_REGISTER_BLOCK_ADDR: *mut () = 0x4000_A000 as *mut ();
pub(crate) const FDCAN2_REGISTER_BLOCK_ADDR: *mut () = 0x4000_A400 as *mut ();
pub(crate) const FDCAN3_REGISTER_BLOCK_ADDR: *mut () = 0x4000_D400 as *mut ();
/// Start of the FDCAN message RAM.
pub(crate) const FDCAN_MSGRAM_ADDR: *mut u32 = 0x4000_AC00 as *mut u32;
/// Message RAM size in 32-bit words.
pub(crate) const FDCAN_MSGRAM_LEN_WORDS: usize = 2560;
#[cfg(feature = "rcc")]
pub(crate) const RCC_REGISTER_BLOCK_ADDR: *mut () = 0x5802_4400 as *mut ();
/// FDCAN clock enable, reset and kernel clock selection. One set for all instances.
#[cfg(feature = "rcc")]
pub(crate) mod rcc_fdcan {
    use crate::pac::rcc::Rcc;
    #[inline]
    pub(crate) fn is_enabled(rcc: Rcc) -> bool {
        rcc.apb1henr().read().fdcanen()
    }
    #[inline]
    pub(crate) fn set_enabled(rcc: Rcc, enabled: bool) {
        rcc.apb1henr().modify(|w| w.set_fdcanen(enabled));
    }
    #[inline]
    pub(crate) fn set_reset(rcc: Rcc, reset: bool) {
        rcc.apb1hrstr().modify(|w| w.set_fdcanrst(reset));
    }
    #[inline]
    pub(crate) fn kernel_clock(rcc: Rcc) -> crate::pac::rcc::vals::Fdcansel {
        rcc.d2ccip1r().read().fdcansel()
    }
}
