// Generated by tools/gen-pac from stm32-metapac 21.0.0 (src/chips/stm32g0b1ce/metadata.rs).
// Do not edit by hand: change tools/gen-pac and re-run it (FEATURES.md P7a).

//! Addresses and FDCAN RCC bits for `g0` (reference chip STM32G0B1CE). FDCAN register version `fdcan_v1`.
pub(crate) const FDCAN1_REGISTER_BLOCK_ADDR: *mut () = 0x4000_6400 as *mut ();
pub(crate) const FDCAN2_REGISTER_BLOCK_ADDR: *mut () = 0x4000_6800 as *mut ();
/// Start of the FDCAN message RAM.
pub(crate) const FDCAN_MSGRAM_ADDR: *mut u32 = 0x4000_B400 as *mut u32;
/// Message RAM size in 32-bit words.
pub(crate) const FDCAN_MSGRAM_LEN_WORDS: usize = 512;
#[cfg(feature = "rcc")]
pub(crate) const RCC_REGISTER_BLOCK_ADDR: *mut () = 0x4002_1000 as *mut ();
/// FDCAN clock enable, reset and kernel clock selection. One set for all instances.
#[cfg(feature = "rcc")]
pub(crate) mod rcc_fdcan {
    use crate::pac::rcc::Rcc;
    #[inline]
    pub(crate) fn is_enabled(rcc: Rcc) -> bool {
        rcc.apbenr1().read().fdcanen()
    }
    #[inline]
    pub(crate) fn set_enabled(rcc: Rcc, enabled: bool) {
        rcc.apbenr1().modify(|w| w.set_fdcanen(enabled));
    }
    #[inline]
    pub(crate) fn set_reset(rcc: Rcc, reset: bool) {
        rcc.apbrstr1().modify(|w| w.set_fdcanrst(reset));
    }
    #[inline]
    pub(crate) fn kernel_clock(rcc: Rcc) -> crate::pac::rcc::vals::Fdcansel {
        rcc.ccipr2().read().fdcansel()
    }
}
