//! Register access layer.
//!
//! Everything except `message_ram`, `tests` and the `variant` modules below is generated by `tools/gen-pac`
//! from a pinned `stm32-metapac` release (chiptool output and chip metadata from stm32-data). Don't edit the
//! generated files by hand, change the generator instead (FEATURES.md P7a).
//!
//! Two FDCAN register maps exist:
//! - `fdcan_h7`: full Bosch M_CAN (STM32H7), configurable message RAM, dedicated RX/TX buffers, TTCAN.
//! - `fdcan_v1`: FDCAN "lite" (STM32G0, G4, L5, H5), fixed message RAM layout. Registers from 0x80 on and most
//!   IR/IE/ILS bit positions differ from the H7 map.
//!
//! `pac::fdcan` is the one for the selected chip.
//!
//! The generated modules get the same lint allowances as in stm32-metapac's `lib.rs`.

#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod common;
pub mod message_ram;

#[cfg(feature = "h7")]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod fdcan_h7;
#[cfg(feature = "h7")]
pub use fdcan_h7 as fdcan;

#[cfg(feature = "g0")]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod fdcan_v1;
#[cfg(feature = "g0")]
pub use fdcan_v1 as fdcan;

// Trimmed by the generator to the registers and fields the driver uses.
#[cfg(all(feature = "rcc", feature = "g0"))]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub(crate) mod rcc_g0;
#[cfg(all(feature = "rcc", feature = "g0"))]
pub(crate) use rcc_g0 as rcc;

#[cfg(all(feature = "rcc", feature = "h7"))]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub(crate) mod rcc_h7;
#[cfg(all(feature = "rcc", feature = "h7"))]
pub(crate) use rcc_h7 as rcc;

// Addresses and FDCAN RCC bits, generated from stm32-metapac's chip metadata.
#[cfg(feature = "g0")]
#[rustfmt::skip]
pub(crate) mod mapping_g0;
#[cfg(feature = "g0")]
pub(crate) use mapping_g0 as mapping;

#[cfg(feature = "h7")]
#[rustfmt::skip]
pub(crate) mod mapping_h7;
#[cfg(feature = "h7")]
pub(crate) use mapping_h7 as mapping;

/// Differences between the full and lite cores that the generated register types can't express.
#[cfg(feature = "h7")]
pub(crate) mod variant {
    /// One bit per TX buffer (32), for TXBTIE / TXBCIE.
    pub(crate) const TX_BUFFERS_ALL: u32 = 0xFFFF_FFFF;
}

/// Differences between the full and lite cores that the generated register types can't express.
#[cfg(not(feature = "h7"))]
pub(crate) mod variant {
    /// One bit per TX buffer (3), for TXBTIE / TXBCIE.
    pub(crate) const TX_BUFFERS_ALL: u32 = 0b111;
}

pub(crate) use mapping::*;

#[cfg(test)]
mod tests;
