//! Register access layer.
//!
//! Everything except `message_ram` and the `mapping` / `variant` modules below is generated by
//! `tools/gen_pac.py` from a pinned `stm32-metapac` release (chiptool output from stm32-data). Don't edit the
//! generated files by hand, change the generator instead (FEATURES.md P7a).
//!
//! Two FDCAN register maps exist:
//! - `fdcan_h7`: full Bosch M_CAN (STM32H7), configurable message RAM, dedicated RX/TX buffers, TTCAN.
//! - `fdcan_v1`: FDCAN "lite" (STM32G0, G4, L5, H5), fixed message RAM layout. Registers from 0x80 on and most
//!   IR/IE/ILS bit positions differ from the H7 map.
//!
//! `pac::fdcan` is the one for the selected chip.
//!
//! The generated modules get the same lint allowances as in stm32-metapac's `lib.rs`.

#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod common;
pub mod message_ram;

#[cfg(feature = "h7")]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod fdcan_h7;
#[cfg(feature = "h7")]
pub use fdcan_h7 as fdcan;

#[cfg(feature = "g0")]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub mod fdcan_v1;
#[cfg(feature = "g0")]
pub use fdcan_v1 as fdcan;

// Trimmed by the generator to the registers and fields the driver uses.
#[cfg(all(feature = "rcc", feature = "g0"))]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub(crate) mod rcc_g0;
#[cfg(all(feature = "rcc", feature = "g0"))]
pub(crate) use rcc_g0 as rcc;

#[cfg(all(feature = "rcc", feature = "h7"))]
#[rustfmt::skip]
#[allow(non_camel_case_types, non_snake_case, unused, clippy::upper_case_acronyms)]
pub(crate) mod rcc_h7;
#[cfg(all(feature = "rcc", feature = "h7"))]
pub(crate) use rcc_h7 as rcc;

// Addresses are cross-checked against stm32-metapac by `tools/gen_pac.py`.
#[cfg(feature = "g0")]
pub(crate) mod mapping {
    #[cfg(feature = "rcc")]
    pub(crate) const RCC_REGISTER_BLOCK_ADDR: *mut () = 0x4002_1000 as *mut ();
    pub(crate) const FDCAN1_REGISTER_BLOCK_ADDR: *mut () = 0x4000_6400 as *mut ();
    pub(crate) const FDCAN2_REGISTER_BLOCK_ADDR: *mut () = 0x4000_6800 as *mut ();
    pub(crate) const FDCAN_MSGRAM_ADDR: *mut u32 = 0x4000_B400 as *mut u32;
    pub(crate) const FDCAN_MSGRAM_LEN_WORDS: usize = 512;
}

#[cfg(feature = "h7")]
pub(crate) mod mapping {
    #[cfg(feature = "rcc")]
    pub(crate) const RCC_REGISTER_BLOCK_ADDR: *mut () = 0x5802_4400 as *mut ();
    pub(crate) const FDCAN1_REGISTER_BLOCK_ADDR: *mut () = 0x4000_A000 as *mut ();
    pub(crate) const FDCAN2_REGISTER_BLOCK_ADDR: *mut () = 0x4000_A400 as *mut ();
    pub(crate) const FDCAN3_REGISTER_BLOCK_ADDR: *mut () = 0x4000_D400 as *mut ();
    // pub(crate) const FDCAN_CCU_REGISTER_BLOCK_ADDR: *mut () = 0x4000_A800 as *mut ();
    pub(crate) const FDCAN_MSGRAM_ADDR: *mut u32 = 0x4000_AC00 as *mut u32;
    pub(crate) const FDCAN_MSGRAM_LEN_WORDS: usize = 2560;
}

/// Differences between the full and lite cores that the generated register types can't express.
#[cfg(all(feature = "asynchronous", feature = "h7"))]
pub(crate) mod variant {
    /// All defined IR / IE bits (IR bits 29:0, RM0468 FDCAN_IR, Bosch M_CAN user manual IR).
    pub(crate) const IR_ALL: u32 = 0x3FFF_FFFF;
    /// One bit per TX buffer (32), for TXBTIE / TXBCIE.
    pub(crate) const TX_BUFFERS_ALL: u32 = 0xFFFF_FFFF;
}

/// Differences between the full and lite cores that the generated register types can't express.
#[cfg(all(feature = "asynchronous", feature = "g0"))]
pub(crate) mod variant {
    /// All defined IR / IE bits (IR bits 23:0, RM0444 FDCAN_IR).
    pub(crate) const IR_ALL: u32 = 0x00FF_FFFF;
    /// One bit per TX buffer (3), for TXBTIE / TXBCIE.
    pub(crate) const TX_BUFFERS_ALL: u32 = 0b111;
}

pub(crate) use mapping::*;

#[cfg(test)]
mod tests;
