// Generated by tools/gen-pac from stm32-metapac 21.0.0 (src/peripherals/rcc_h7.rs, trimmed).
// Do not edit by hand: change tools/gen-pac and re-run it (FEATURES.md P7a).

#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
///Reset and clock control
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Rcc {
    ptr: *mut u8,
}
unsafe impl Send for Rcc {}
unsafe impl Sync for Rcc {}
impl Rcc {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///clock control register
    #[inline(always)]
    pub const fn cr(self) -> crate::pac::common::Reg<regs::Cr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x0usize) as _) }
    }
    ///RCC PLLs Configuration Register
    #[inline(always)]
    pub const fn pllcfgr(
        self,
    ) -> crate::pac::common::Reg<regs::Pllcfgr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x2cusize) as _) }
    }
    ///RCC Domain 2 Kernel Clock Configuration Register
    #[inline(always)]
    pub const fn d2ccip1r(
        self,
    ) -> crate::pac::common::Reg<regs::D2ccip1r, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x50usize) as _) }
    }
    ///RCC APB1 Peripheral Reset Register
    #[inline(always)]
    pub const fn apb1hrstr(
        self,
    ) -> crate::pac::common::Reg<regs::Apb1hrstr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x94usize) as _) }
    }
    ///RCC APB1 Clock Register
    #[inline(always)]
    pub const fn apb1henr(
        self,
    ) -> crate::pac::common::Reg<regs::Apb1henr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0xecusize) as _) }
    }
}
pub mod regs {
    ///RCC APB1 Clock Register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Apb1henr(pub u32);
    impl Apb1henr {
        ///FDCAN Peripheral Clocks Enable
        #[inline(always)]
        pub const fn fdcanen(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///FDCAN Peripheral Clocks Enable
        #[inline(always)]
        pub fn set_fdcanen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
    }
    impl Default for Apb1henr {
        #[inline(always)]
        fn default() -> Apb1henr {
            Apb1henr(0)
        }
    }
    impl core::fmt::Debug for Apb1henr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Apb1henr").field("fdcanen", &self.fdcanen()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Apb1henr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Apb1henr {{ fdcanen: {=bool:?} }}", self.fdcanen())
        }
    }
    ///RCC APB1 Peripheral Reset Register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Apb1hrstr(pub u32);
    impl Apb1hrstr {
        ///FDCAN block reset
        #[inline(always)]
        pub const fn fdcanrst(&self) -> bool {
            let val = (self.0 >> 8usize) & 0x01;
            val != 0
        }
        ///FDCAN block reset
        #[inline(always)]
        pub fn set_fdcanrst(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize);
        }
    }
    impl Default for Apb1hrstr {
        #[inline(always)]
        fn default() -> Apb1hrstr {
            Apb1hrstr(0)
        }
    }
    impl core::fmt::Debug for Apb1hrstr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Apb1hrstr").field("fdcanrst", &self.fdcanrst()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Apb1hrstr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Apb1hrstr {{ fdcanrst: {=bool:?} }}", self.fdcanrst())
        }
    }
    ///clock control register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cr(pub u32);
    impl Cr {
        ///HSE clock enable
        #[inline(always)]
        pub const fn hseon(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///HSE clock enable
        #[inline(always)]
        pub fn set_hseon(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for Cr {
        #[inline(always)]
        fn default() -> Cr {
            Cr(0)
        }
    }
    impl core::fmt::Debug for Cr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Cr").field("hseon", &self.hseon()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Cr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Cr {{ hseon: {=bool:?} }}", self.hseon())
        }
    }
    ///RCC Domain 2 Kernel Clock Configuration Register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct D2ccip1r(pub u32);
    impl D2ccip1r {
        ///FDCAN kernel clock source selection
        #[inline(always)]
        pub const fn fdcansel(&self) -> super::vals::Fdcansel {
            let val = (self.0 >> 28usize) & 0x03;
            super::vals::Fdcansel::from_bits(val as u8)
        }
        ///FDCAN kernel clock source selection
        #[inline(always)]
        pub fn set_fdcansel(&mut self, val: super::vals::Fdcansel) {
            self.0 = (self.0 & !(0x03 << 28usize))
                | (((val.to_bits() as u32) & 0x03) << 28usize);
        }
    }
    impl Default for D2ccip1r {
        #[inline(always)]
        fn default() -> D2ccip1r {
            D2ccip1r(0)
        }
    }
    impl core::fmt::Debug for D2ccip1r {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("D2ccip1r").field("fdcansel", &self.fdcansel()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for D2ccip1r {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "D2ccip1r {{ fdcansel: {:?} }}", self.fdcansel())
        }
    }
    ///RCC PLLs Configuration Register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pllcfgr(pub u32);
    impl Pllcfgr {
        ///PLL1 DIVQ divider output enable
        #[inline(always)]
        pub const fn divqen(&self, n: usize) -> bool {
            assert!(n < 3usize);
            let offs = 17usize + n * 3usize;
            let val = (self.0 >> offs) & 0x01;
            val != 0
        }
        ///PLL1 DIVQ divider output enable
        #[inline(always)]
        pub fn set_divqen(&mut self, n: usize, val: bool) {
            assert!(n < 3usize);
            let offs = 17usize + n * 3usize;
            self.0 = (self.0 & !(0x01 << offs)) | (((val as u32) & 0x01) << offs);
        }
    }
    impl Default for Pllcfgr {
        #[inline(always)]
        fn default() -> Pllcfgr {
            Pllcfgr(0)
        }
    }
    impl core::fmt::Debug for Pllcfgr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pllcfgr")
                .field("divqen[0]", &self.divqen(0usize))
                .field("divqen[1]", &self.divqen(1usize))
                .field("divqen[2]", &self.divqen(2usize))
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pllcfgr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(
                f,
                "Pllcfgr {{ divqen[0]: {=bool:?}, divqen[1]: {=bool:?}, divqen[2]: {=bool:?} }}",
                self.divqen(0usize), self.divqen(1usize), self.divqen(2usize)
            )
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Fdcansel {
        ///HSE selected as peripheral clock
        HSE = 0x0,
        ///pll1_q selected as peripheral clock
        PLL1_Q = 0x01,
        ///pll2_q selected as peripheral clock
        PLL2_Q = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl Fdcansel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Fdcansel {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Fdcansel {
        #[inline(always)]
        fn from(val: u8) -> Fdcansel {
            Fdcansel::from_bits(val)
        }
    }
    impl From<Fdcansel> for u8 {
        #[inline(always)]
        fn from(val: Fdcansel) -> u8 {
            Fdcansel::to_bits(val)
        }
    }
}
