// Generated by tools/gen-pac from stm32-metapac 21.0.0 (src/peripherals/rcc_g0x1.rs, trimmed).
// Do not edit by hand: change tools/gen-pac and re-run it (FEATURES.md P7a).

#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
///Reset and clock control
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Rcc {
    ptr: *mut u8,
}
unsafe impl Send for Rcc {}
unsafe impl Sync for Rcc {}
impl Rcc {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
    ///Clock control register
    #[inline(always)]
    pub const fn cr(self) -> crate::pac::common::Reg<regs::Cr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x0usize) as _) }
    }
    ///PLL configuration register
    #[inline(always)]
    pub const fn pllcfgr(
        self,
    ) -> crate::pac::common::Reg<regs::Pllcfgr, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x0cusize) as _) }
    }
    ///APB peripheral reset register 1
    #[inline(always)]
    pub const fn apbrstr1(
        self,
    ) -> crate::pac::common::Reg<regs::Apbrstr1, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x2cusize) as _) }
    }
    ///APB peripheral clock enable register 1
    #[inline(always)]
    pub const fn apbenr1(
        self,
    ) -> crate::pac::common::Reg<regs::Apbenr1, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x3cusize) as _) }
    }
    ///Peripherals independent clock configuration register 2
    #[inline(always)]
    pub const fn ccipr2(
        self,
    ) -> crate::pac::common::Reg<regs::Ccipr2, crate::pac::common::RW> {
        unsafe { crate::pac::common::Reg::from_ptr(self.ptr.add(0x58usize) as _) }
    }
}
pub mod regs {
    ///APB peripheral clock enable register 1
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Apbenr1(pub u32);
    impl Apbenr1 {
        ///USBEN
        #[inline(always)]
        pub const fn fdcanen(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        ///USBEN
        #[inline(always)]
        pub fn set_fdcanen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize);
        }
    }
    impl Default for Apbenr1 {
        #[inline(always)]
        fn default() -> Apbenr1 {
            Apbenr1(0)
        }
    }
    impl core::fmt::Debug for Apbenr1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Apbenr1").field("fdcanen", &self.fdcanen()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Apbenr1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Apbenr1 {{ fdcanen: {=bool:?} }}", self.fdcanen())
        }
    }
    ///APB peripheral reset register 1
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Apbrstr1(pub u32);
    impl Apbrstr1 {
        ///FDCANRST
        #[inline(always)]
        pub const fn fdcanrst(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        ///FDCANRST
        #[inline(always)]
        pub fn set_fdcanrst(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize);
        }
    }
    impl Default for Apbrstr1 {
        #[inline(always)]
        fn default() -> Apbrstr1 {
            Apbrstr1(0)
        }
    }
    impl core::fmt::Debug for Apbrstr1 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Apbrstr1").field("fdcanrst", &self.fdcanrst()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Apbrstr1 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Apbrstr1 {{ fdcanrst: {=bool:?} }}", self.fdcanrst())
        }
    }
    ///Peripherals independent clock configuration register 2
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Ccipr2(pub u32);
    impl Ccipr2 {
        ///FDCANSEL
        #[inline(always)]
        pub const fn fdcansel(&self) -> super::vals::Fdcansel {
            let val = (self.0 >> 8usize) & 0x03;
            super::vals::Fdcansel::from_bits(val as u8)
        }
        ///FDCANSEL
        #[inline(always)]
        pub fn set_fdcansel(&mut self, val: super::vals::Fdcansel) {
            self.0 = (self.0 & !(0x03 << 8usize))
                | (((val.to_bits() as u32) & 0x03) << 8usize);
        }
    }
    impl Default for Ccipr2 {
        #[inline(always)]
        fn default() -> Ccipr2 {
            Ccipr2(0)
        }
    }
    impl core::fmt::Debug for Ccipr2 {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Ccipr2").field("fdcansel", &self.fdcansel()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Ccipr2 {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Ccipr2 {{ fdcansel: {:?} }}", self.fdcansel())
        }
    }
    ///Clock control register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Cr(pub u32);
    impl Cr {
        ///HSE clock enable
        #[inline(always)]
        pub const fn hseon(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        ///HSE clock enable
        #[inline(always)]
        pub fn set_hseon(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
    }
    impl Default for Cr {
        #[inline(always)]
        fn default() -> Cr {
            Cr(0)
        }
    }
    impl core::fmt::Debug for Cr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Cr").field("hseon", &self.hseon()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Cr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Cr {{ hseon: {=bool:?} }}", self.hseon())
        }
    }
    ///PLL configuration register
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pllcfgr(pub u32);
    impl Pllcfgr {
        ///PLLQCLK clock output enable
        #[inline(always)]
        pub const fn pllqen(&self) -> bool {
            let val = (self.0 >> 24usize) & 0x01;
            val != 0
        }
        ///PLLQCLK clock output enable
        #[inline(always)]
        pub fn set_pllqen(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize);
        }
    }
    impl Default for Pllcfgr {
        #[inline(always)]
        fn default() -> Pllcfgr {
            Pllcfgr(0)
        }
    }
    impl core::fmt::Debug for Pllcfgr {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pllcfgr").field("pllqen", &self.pllqen()).finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pllcfgr {
        fn format(&self, f: defmt::Formatter) {
            defmt::write!(f, "Pllcfgr {{ pllqen: {=bool:?} }}", self.pllqen())
        }
    }
}
pub mod vals {
    #[repr(u8)]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
    #[cfg_attr(feature = "defmt", derive(defmt::Format))]
    pub enum Fdcansel {
        ///PCLK used as FDCAN clock source
        PCLK1 = 0x0,
        ///PLLQCLK used as FDCAN clock source
        PLL1_Q = 0x01,
        ///HSE used as FDCAN clock source
        HSE = 0x02,
        _RESERVED_3 = 0x03,
    }
    impl Fdcansel {
        #[inline(always)]
        pub const fn from_bits(val: u8) -> Fdcansel {
            unsafe { core::mem::transmute(val & 0x03) }
        }
        #[inline(always)]
        pub const fn to_bits(self) -> u8 {
            unsafe { core::mem::transmute(self) }
        }
    }
    impl From<u8> for Fdcansel {
        #[inline(always)]
        fn from(val: u8) -> Fdcansel {
            Fdcansel::from_bits(val)
        }
    }
    impl From<Fdcansel> for u8 {
        #[inline(always)]
        fn from(val: Fdcansel) -> u8 {
            Fdcansel::to_bits(val)
        }
    }
}
