//! Generates mcan's register access layer (`src/pac`) from a pinned `stm32-metapac` (FEATURES.md P7a).
//!
//! ```sh
//! cargo run --manifest-path tools/gen-pac/Cargo.toml            # (re)generate src/pac
//! cargo run --manifest-path tools/gen-pac/Cargo.toml -- --check # fail if src/pac is out of date
//! ```
//!
//! What it produces:
//! - `common.rs` and `fdcan_<version>.rs`: copied verbatim from metapac (only the `crate::common` path is
//!   rewritten), so they can be diffed against upstream.
//! - `rcc_<feature>.rs`: metapac's RCC block parsed with `syn` and trimmed to the registers / fields the
//!   driver uses. Debug and defmt impls are kept, filtered to the remaining fields.
//! - `mapping_<feature>.rs`: addresses and the FDCAN RCC enable / reset / kernel-clock bits, taken from
//!   metapac's per-chip metadata.
//!
//! The metapac version is pinned in this crate's `Cargo.toml` and checksum-verified through `Cargo.lock`.

mod chips;
mod emit;
mod metadata;
mod trim;

use anyhow::{Context, Result, bail};
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

/// First line of every generated file. Also used to find stale generated files.
const GENERATED_MARKER: &str = "// Generated by tools/gen-pac";

fn main() -> ExitCode {
    match run() {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::FAILURE,
        Err(e) => {
            eprintln!("error: {e:#}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<bool> {
    let check = match std::env::args().nth(1).as_deref() {
        None => false,
        Some("--check") => true,
        Some(other) => bail!("unknown argument {other:?}, expected --check or nothing"),
    };

    let repo = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()?;
    let out_dir = repo.join("src/pac");
    let (metapac, version) = locate_metapac()?;

    let files = generate(&metapac, &version)?;
    sync(&out_dir, &files, check)
}

/// Every output file name with its content.
fn generate(metapac: &Path, version: &str) -> Result<BTreeMap<String, String>> {
    let mut files = BTreeMap::new();
    let header = |source: &str, how: &str| {
        format!(
            "{GENERATED_MARKER} from stm32-metapac {version} ({source}{how}).\n\
             // Do not edit by hand: change tools/gen-pac and re-run it (FEATURES.md P7a).\n\n"
        )
    };
    let read = |rel: &str| -> Result<String> {
        let text =
            std::fs::read_to_string(metapac.join(rel)).with_context(|| format!("reading {rel}"))?;
        Ok(text.replace("crate::common::", "crate::pac::common::"))
    };

    files.insert(
        "common.rs".into(),
        header("src/common.rs", "") + &read("src/common.rs")?,
    );

    let mut fdcan_versions = BTreeSet::new();
    for chip in chips::CHIPS {
        let info = metadata::ChipInfo::load(metapac, chip)?;
        fdcan_versions.insert(info.fdcan_version.clone());

        let rcc_src = format!("src/peripherals/rcc_{}.rs", info.rcc_version);
        let keep = chip.rcc_keep(&info);
        let trimmed = trim::trim_rcc(&read(&rcc_src)?, &keep)
            .with_context(|| format!("trimming {rcc_src}"))?;
        files.insert(
            format!("rcc_{}.rs", chip.feature),
            header(&rcc_src, ", trimmed") + &trimmed,
        );

        let mapping = emit::mapping(chip, &info, &trimmed)?;
        let source = format!("src/chips/{}/metadata.rs", chip.chip);
        files.insert(
            format!("mapping_{}.rs", chip.feature),
            header(&source, "") + &mapping,
        );
    }
    for v in fdcan_versions {
        let src = format!("src/peripherals/can_{v}.rs");
        files.insert(format!("{v}.rs"), header(&src, "") + &read(&src)?);
    }
    Ok(files)
}

/// Writes (or, with `check`, compares) the generated files and removes stale ones. Returns false on a diff
/// in check mode.
fn sync(out_dir: &Path, files: &BTreeMap<String, String>, check: bool) -> Result<bool> {
    let mut ok = true;
    for (name, text) in files {
        let path = out_dir.join(name);
        if std::fs::read_to_string(&path).ok().as_deref() == Some(text.as_str()) {
            continue;
        }
        if check {
            eprintln!("src/pac/{name} is out of date");
            ok = false;
        } else {
            std::fs::write(&path, text)?;
            println!("wrote src/pac/{name}");
        }
    }
    for entry in std::fs::read_dir(out_dir)? {
        let path = entry?.path();
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default()
            .to_string();
        let generated =
            std::fs::read_to_string(&path).is_ok_and(|t| t.starts_with(GENERATED_MARKER));
        if generated && !files.contains_key(&name) {
            if check {
                eprintln!("src/pac/{name} is a stale generated file");
                ok = false;
            } else {
                std::fs::remove_file(&path)?;
                println!("removed stale src/pac/{name}");
            }
        }
    }
    if check && !ok {
        eprintln!("run `cargo run --manifest-path tools/gen-pac/Cargo.toml` to regenerate");
    }
    Ok(ok)
}

/// Source directory and version of the pinned stm32-metapac, resolved (and downloaded if needed) by cargo.
fn locate_metapac() -> Result<(PathBuf, String)> {
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR")).join("Cargo.toml");
    let out = std::process::Command::new(cargo)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--locked",
            "--manifest-path",
        ])
        .arg(&manifest)
        .output()
        .context("running cargo metadata")?;
    if !out.status.success() {
        bail!(
            "cargo metadata failed:\n{}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    let json: serde_json::Value = serde_json::from_slice(&out.stdout)?;
    let pkg = json["packages"]
        .as_array()
        .and_then(|p| p.iter().find(|p| p["name"] == "stm32-metapac"))
        .context("stm32-metapac not found in cargo metadata")?;
    let manifest_path = pkg["manifest_path"].as_str().context("no manifest_path")?;
    let dir = Path::new(manifest_path)
        .parent()
        .context("bad manifest_path")?
        .to_path_buf();
    let version = pkg["version"].as_str().context("no version")?.to_string();
    Ok((dir, version))
}
